export const webDevSeedData = [
    {id:1, name: 'Creetures', date: '2023', description:  `The application is built using React.js, JavaScript, TypeScript, Chakra UI, and Supabase for backend development.
    We implemented a responsive and intuitive user interface to ensure a seamless experience across various devices.Developed a dynamic habit management system allowing users to add, edit, and delete habits effortlessly.Employed TypeScript to enhance code maintainability, catch potential errors during development, and improve overall code quality.Leveraged React Context API for efficient state management, ensuring a streamlined flow of data throughout the application.`,link: 'https://github.com/Habit-tr/creetures-react', src:"https://i.ibb.co/L597GZH/cute-blue-pink-play-dough-monsters.jpg",imgs:['https://i.ibb.co/pbJcP0q/Dashboard-Page.png','https://i.ibb.co/8rQ2dwk/All-Challenges-page.png', 'https://i.ibb.co/0cS76mh/Single-Challenge-page.png'], tag:"web"},

    {id:2, name: 'OnlineShop', date: '2023', description: 'Building an online shopping app in a coding bootcamp with React.js, Bootstrap, Sequelize, and PostgreSQL was an enriching experience. For the backend, we opted for Sequelize as our ORM (Object-Relational Mapping) tool and PostgreSQL as the database management system. Sequelize streamlined the communication between our Node.js server and the PostgreSQL database, making it easier to define models, relationships, and perform CRUD operations. We integrated authentication features using React.js on the frontend and implemented secure login and registration processes. Leveraging React.js allowed us to create a dynamic shopping cart that updated in real-time as users added or removed items. ', link: 'https://github.com/Maverick-Merchants/grace-hopper', src:"https://i.ibb.co/f0jp9nd/online-shopping-4236450-640.jpg",imgs:['https://i.ibb.co/hckrbBF/Untitled-Workspace.png','https://i.ibb.co/n8Y9f1Y/Home.png', 'https://i.ibb.co/S0kHtM3/cart.png'],tag:"web"},

    {id:3, name: 'Crafting My Digital Presence', date: '2023', description: 'Creating my personal website with React.js, GSAP, and Three.js was a rewarding journey that allowed me to showcase my skills and projects in a visually compelling way. The combination of these powerful technologies empowered me to create a digital space that not only reflected my abilities but also provided visitors with an immersive and enjoyable exploration of my work. To add a layer of dynamism and interactivity, I incorporated GSAP for animations. The GreenSock Animation Platform provided a powerful and intuitive way to create smooth transitions, stunning effects, and captivating visual elements. To push the boundaries of creativity, I integrated Three.js to include 3D visualizations and interactive elements. Building my personal website was an iterative process. Continuous testing and optimization were key to refining the user interface, enhancing performance, and ensuring a seamless browsing experience. ',link: 'https://github.com/siminpaksirat/personal-web', src:"https://i.ibb.co/7t03cQq/Screenshot-2023-12-14-at-3-25-10-PM.png",imgs:['https://i.ibb.co/nnB5p7B/dynamics.png','https://i.ibb.co/NSbxyHf/Home-1.png', 'https://i.ibb.co/xz1LVG8/other-pages.png'], tag:"web"},
]


export const architectureSeedData = [
    {id:1, name: 'Jaddeh Complex', date: '2015', description: 'A chief consideration of this project is to maximize the views looking towards the sea. The project consists of two main towers that are rotated to provide views on two different sides. These two main towers are connected through a series of bridges that extend along the two sea-facing sides of the towers. The project is divided into two parts: residential and hotel apartments. The unique design allows for separation of access for both types of occupants. In addition, the building contains retail spaces on the ground level and its two mezzanine floors as well as a restaurant on the 10th floor and a health club on the 12th floor', src:"https://i.ibb.co/xstL8zK/jaddeh-01.jpg", imgs:['https://i.ibb.co/5BF5jQ9/jaddeh-02.jpg','https://i.ibb.co/g3psndP/jaddeh-03.jpg', 'https://i.ibb.co/jvHgj27/jaddeh-04.jpg'], tag:"arch"},

    {id:2, name: 'Iceland Visitor Center', date: '2020', description: 'The Black Lava Visitor Center communicates the beauty of the surrounding nature by embracing its immediate surroundings. Its unique appearance attracts visitors and simultaneously works as a catalyst for indoor and outdoor activities. The building form is inspired by traditional Icelandic turf houses, which is united with a modern approach to create a unique design, while also featuring a sustainable insulation system and an elevated walkway with a panoramic view of the surrounding nature. The plaza within the building has three different zones. The cafe and kitchen, outdoor garden and playground, and a small office along with a gift shop area.The building is slightly raised above the ground to minimize soil erosion. The facade has to endure harsh weather and thus it is constructed with maintenance-free burned wood, a traditional Japanese technique incorporated into the Iceland context', src:'https://i.ibb.co/qBRQXKh/iceland-center-01.jpg', imgs:['https://i.ibb.co/JRq97Gv/plan.png','https://i.ibb.co/F4M71gs/iceland-center-01.jpg', 'https://i.ibb.co/QXpfcHF/iceland-center-02.jpg'], tag:"arch"},

    {id:3, name: 'The ways of Looking ... Masked', date: '2016', description: 'The human figure creates a dynamic configuration and composition with its surrounding space. Studying the human figure and its movements with the help of Maya software, I explored the potential spaces that could exist throughout the studio. Examining art projects, literature, and architectural projects, I developed a concept of how the human figure and its movements could be perceived within architectural elements and boundaries. I applied the concept to other elements of our living environment, such as trees, and planned the space based on the concept of looking masked, as if the architecture is narrating a story of figures, objects, and other surroundings in an obscured, masked fashion. The effects that are created by this concept are in some ways mysterious or formally making abstract compositions, which adds a certain quality to the space', src:'https://i.ibb.co/7Nb9Dwq/studiol-01.jpg', imgs:['https://i.ibb.co/QkkKn9P/studiol-01.jpg','https://i.ibb.co/vc13jhq/studiol-03.jpg', 'https://i.ibb.co/qxfYj80/studiol-04.jpg'], tag:"arch"},

    {id:4, name: 'A Church, A Barn, and A house!', date: '2019', description: 'Some building types have similar features that can be scaled and aligned to make composite buildings. Common material: Grain silos and houses are frequently made of brick. The model scales down the silo to house size and the full exterior is made of brick. Common form: The barn, church, and house have similar forms. All three are often extruded symmetrical elevation profiles—only their roofs vary. In the model, they are scaled to standardize their heights and align them to make a triangular building with different cross sections in each leg and a folded two-part elevation in each corner. As the result the following qualities have been created. Common form: The Ledoux villa and the Mayan temple have stepped, pyramidal forms—often multiple, overlapping volumes. The model and plan show a villa size house with a Mayan temples steps', src:"https://i.ibb.co/Kx4bh6T/studiolv-04.jpg",imgs:['https://i.ibb.co/KN0G5gd/studiolv-03.jpg','https://i.ibb.co/KDdNx8C/studiolv-05.jpg', 'https://i.ibb.co/TMRT1v4/studiolv-02.jpg'], tag:"arch"},

    {id:5, name: 'Yoga Cabin', date: '2020', description: 'My work, “Reconnection Cabin,” seeks to provide an environment that will help its occupant recenter herself within the world. The space is constructed so that a person is brought into contact with three different planes simultaneously: the sky, nature, and the earth underneath. Through the exposure to these three elements, the cabin offers its guest the chance to experience regrounding (earth), renewal (nature), and reappreciation of the vastness of the universe (sky), ultimately leading to reconnection to the self and to the world.This effect on the occupant is achieved through the narrative that the architectural elements of the cabin create. The vertical axis of sky -> nature -> earth is constructed through the arrangement of the skylight, windows, and glass floor. The horizontal axis, nature, creates poetic feelings of wonder at the beautiful surroudings, leading to a more peaceful mindset.', src:'https://i.ibb.co/yqWV8sj/yoga-cabin-01.jpg',imgs:['https://i.ibb.co/58VHB6X/yoga-cabin-01.jpg','https://i.ibb.co/Twjk6Yv/yoga-cabin-02.jpg'], tag:"arch"},

    {id:6, name: 'Future Home', date: '2019', description: 'Whereas the “smart” homes of today are filled with “smart” objects marketed heavily by technology companies that provide infinitesimally incremental improvements in convenience, the intelligent home of tomorrow will readily adapt to the lifestyle and the dreams of its occupants. Constructed of a flexible, infinitely adaptable material, it can be molded like clay into any form the mind desires. The organic curvature of the surface can adjust to any environment or any life situation.My conception of the intelligent home relies on future technologies that will be developed in the coming decades. The outer surface is made of semi-flexible solar absorbers that will collect energy and store it efficiently. Underneath the solar-absorbing layer is a temperature-cured polymer that can be deformed and reformed whenever desired by using the stored energy gathered by the home’s outer surface. The innermost layer is comprised of semi-flexible insulation that provides a cozy, yet versatile living environment', src:'https://i.ibb.co/CbLZnym/future-house-01.jpg',imgs:['https://i.ibb.co/qpt9fsZ/future-house-02.jpg','https://i.ibb.co/tPrh57y/002.jpg', 'https://i.ibb.co/CbLZnym/future-house-01.jpg'], tag:"arch"},

    {id:7, name: 'Portable Theater', date: '2015', description: 'smaller cities lack the capital’s cultural hubs, and a lot of shows are simply not accessible to a large percentage of the country. The idea of a portable theater was suggested to me by my thesis advisor who is a playwright as well. After researching different methods that could bring this idea into fruition, I chose containers as a standard, portable modular component that can be stacked to create a desirable space, finished with a tensile structure that functions as a roof. The main parts of this structure - the containers and tensile structure - are easily procured and easily transported via highways or railroads and could be assembled in empty lots, suitable for a temporary theater', src:"https://i.ibb.co/DM89YKx/bachelor-thesis-03.jpg",imgs:['https://i.ibb.co/JR3QxPF/bachelor-thesis-01.jpg','https://i.ibb.co/HNVNyF6/bachelor-thesis-02.jpg', 'https://i.ibb.co/6vbyHR1/bachelor-thesis-03.jpg'], tag:"arch"},

    {id:8, name: 'Ur-Form', date: '2019', description: 'Rothko Chapel, located in Houston and opened in 1971, was specifically designed to hold Rothko’s paintings; in other words, the architecture is less visible in order to make the art is more visible. Over the course of one year, our graduate research group studied the dynamics of Andrew Zago’s Ur-form theory, which explores new computer-based technical methods to bring a new generation of architecture into existence. We observed hundreds of important architectural buildings and produced and studied their diagrams. This experience influenced the project diagramming. The project, a re-imagining of the Rothko Chapel, is designed based on two cuboids, rotated in the X, Y, and Z axes, in order to create a non-linear perspective with the artwork, so that the architecture is as loud as art. The main chapel consists of three parts: the four-sided stepped base of the building, the middle ribbon that holds Rothko’s paintings, and the transformed cuboids on top with various angles to bring light and extra dimensions in place', src:'https://i.ibb.co/NC2NndL/masters-thesis-03.jpg',imgs:['https://i.ibb.co/SsyyQ3k/masters-thesis-04.jpg','https://i.ibb.co/QjTHfgy/material-study-03.jpg', 'https://i.ibb.co/dQBXXDQ/masters-thesis-03.jpg'], tag:"arch"},

    {id:9, name: 'Inside / Out', date: '2019', description: 'The project is designed in reverse order in comparison to any typical housing project. The process began by considering furniture, and how it could be arranged in the space regardless of any type of boundaries. Human behavioral processes were studied and were reflected in the arrangement of the furniture. The objects themselves were the determining factor in how the habitat should form and what type of form it should take. In this project, the boundaries (walls, curtains, doors, etc.) took their forms from household objects. The overall guiding concept consists of using larger or smaller formal concepts and applying them, respectively, to smaller or larger elements of the building. One example is the use of a typical house form for a single bedroom. Other examples include a living room shaped as a bigger version of a bay window or a kitchen shaped as a U form. During the next phase, materials and detailing of the project’s formal concept were developed. Material choice was based on how the concept of the project could be projected to both the interior and exterior', src:'https://i.ibb.co/6srYQRb/studioll-01.png',imgs:['https://i.ibb.co/7vF9HsR/studioll-01.png','https://i.ibb.co/RNwxWL3/studioll-03.jpg', 'https://i.ibb.co/PNJ6PgH/studioll-04.jpg'], tag:"arch"},

    {id:10, name: 'Housing', date: '2020', description: 'random random random', src:"https://i.ibb.co/kxrQ5HF/form-study-05.jpg",imgs:['https://i.ibb.co/xKbC1zx/form-study-06.jpg','https://i.ibb.co/zx74N32/form-study-07.jpg', 'https://i.ibb.co/dkj47Qj/form-study-02.jpg'], tag:"arch"},

    {id:11, name: 'Big Urban Building', date: '2018', description: 'Beginning with a current architectural project as a base form (Aldo Rossi’s town hall) and transforming it with computer tools into a new version of what that form could become, I designed a multi-functional complex. I created a sheared version of the actual form as the shadow of the form, where this shadow is a part of the building, with 3.2’ height: it is a tangible form that people could actually interact with, while in reality there is no way to interact and perceive a big building’s form as a whole. The function of the shadow part is an art gallery, which has a metaphoric aspect to it as well. (“How can I be substantial if I do not cast a shadow? I must have a dark side also if I am to be whole.”,C.G.Jung). The rest is formed as different compartments being attached by a long rectangular form. These forms serve as a hotel, office building and commercial complex', src:'https://i.ibb.co/7bT2mcD/studiolll-02.jpg',imgs:['https://i.ibb.co/B46LjW1/studiolll-01.jpg','https://i.ibb.co/7bT2mcD/studiolll-02.jpg', 'https://i.ibb.co/Zz3nWVV/studiolll-03.jpg'], tag:"arch"},

    {id:12, name: 'Fellow of Fellows', date: '2019', description: 'I collaborated with a select group of students with the Garofalo fellow, Anne Dessing, on a research and exhibition project about architectural borders that are not closed off by solid walls, and how segregation and inequality relate to physical architectural borders in contemporary American cities.The team made an atlas of situations we found in the city of Chicago. We photographed the streets and then analyzed their borders. We made drawings in order to understand the spatial consequences of these borders. The exhibition design transformed the relationships between these separated worlds.The exhibition took place at the University of Illinois at Chicago, along with a lecture presentation at Graham Foundation', src:'https://i.ibb.co/sK6wj7w/exhibition-05.jpg',imgs:['https://i.ibb.co/QbhmQVy/exhibition-02.jpg','https://i.ibb.co/TqTtT6C/exhibition-06.jpg', 'https://i.ibb.co/YjMJH8R/Exhibition-Design002.jpg'], tag:"arch"},
]





export const artSeedData = [

    {id:1, name: 'Double Life', date: '2022', description: `Motivated by the artist's nuanced emotional landscape, the artwork is a testament to the dichotomy between the tranquility experienced in the United States and the profound distress evoked by the artist's contemplation of her homeland`, src:"https://i.ibb.co/dpGdrR9/double-life.jpg", imgs:['https://i.ibb.co/Fb00W3r/double-life.jpg'], tag:"art"},

    {id:2, name: 'The Shelve', date: '2021', description: `Envisioned in the spirit of "Columbarium Habitabile" by Alexander Brodsky and Ilya Utkin, the artwork provocatively inquires, "Where do you reside on the shelf?" This contemplative query emerges from a profound exploration of spatial identity and draws inspiration from the thematic resonance found within the aforementioned architectural masterpiece`, src:'https://i.ibb.co/ZmVwkXy/the-shelve.jpg',imgs:['https://i.ibb.co/SmHSgf9/the-shelve.jpg'],tag:"art"},

    {id:3, name: 'Celebrating Evil', date: '2023', description: `This illustrative composition serves as an exploration and commentary on the ominous inevitability inherent in the temporal progression of oppressive regimes. Through a symbolic representation of the celebration of malevolence, the artwork encapsulates the unsettling cadence of a dictatorship's temporal dominance, underscoring the perennial truth that, despite the jubilation of wrongdoing, an ultimate denouement looms inexorably on the horizon with the passage of time`, src:'https://i.ibb.co/rsmbCNf/celebrating-evil.jpg',imgs:['https://i.ibb.co/4NnyR3t/celebrating-evil.jpg'], tag:"art"},

    {id:4, name: 'The Hair', date: '2023', description: `
    In homage to the poignant Women, Life, Freedom movement in Iran, this drawing intricately captures the essence of feminine strength and emancipation. Depicting hands adorned with distinctly feminine characteristics delicately cradling and extending strands of hair, the composition symbolically portrays the pervasive reach of these hands—an allegory for the tireless pursuit of freedom. The image becomes a nuanced exploration of women's agency, resilience, and their collective endeavor to disseminate the symbol of liberated expression amid societal confines.`, src:'https://i.ibb.co/F3YWH5G/the-hair.jpg',imgs:['https://i.ibb.co/Hgg3byX/the-hair.jpg'], tag:"art"},

    {id:5, name: 'Invisible life', date: '2020', description: `
    Derived from the thematic tapestry of V.E. Schwab's literary opus, "The Invisible Life of Addie LaRue," this drawing embodies the existential quandary of a quasi-immortal human entity, eternally veiled in partial obscurity to its own self. Symbolically manifesting as a tower with multilayered dimensions, the artwork not only serves as a visual representation of the protagonist's intrinsic struggle but also invites contemplation on the complex interplay between visibility and introspection within the realm of enduring existence.`, src:'https://i.ibb.co/SNbZsCg/the-invisible-life.jpg',imgs:['https://i.ibb.co/6DLKXwT/the-invisible-life.jpg'], tag:"art"},

    {id:6, name: 'Cloud City', date: '2020', description: `In homage to the artistic influence of Zoe Zenghelis, this drawing, titled "Looking Down at the Sky," crafts a surreal landscape. Within the urban panorama, colossal city structures confine and encapsulate the celestial expanse, interweaving the sky and clouds into the very fabric of metropolitan architecture. Above, a whimsical inversion transpires, as buildings seamlessly amalgamate into ethereal cloud formations, evoking a mesmerizing fusion of the man-made and the celestial, reminiscent of Zenghelis's distinctive approach to reimagining the relationship between the urban and the atmospheric.`, src:'https://i.ibb.co/nCWDW69/cloud-city.jpg',imgs:['https://i.ibb.co/fFp8q1M/cloud-city.jpg'], tag:"art"},

    {id:7, name: 'Dimensions', date: '2022', description: `Entitled "Their Truth," this drawing serves as a contemplative exploration of the deceptive nature of perceived dimensions. Illuminating the notion that the veracity of our visual reality is far from absolute, the artwork unveils a subtler layer beneath the surface. A meticulous inspection reveals a clandestine shadow of malevolence cast upon the wall, inviting the discerning observer to unravel a deeper, obscured reality that challenges the superficial truths presented by the apparent dimensions`, src:'https://i.ibb.co/23CNh7N/dimensions.jpg',imgs:['https://i.ibb.co/sHXXdZW/dimensions.jpg'], tag:"art"},

    {id:8, name: 'Deception', date: '2020', description: `
    Derived from the literary depths of Stendhal's 'The Red and the Black,' this drawing navigates the nuanced terrain of deception. Abstractly illustrating the concept, the artwork unveils a paradoxical scenario: a box adorned with numerous doors ostensibly leading to the outside, yet confined by two enclosing walls within. This symbolic representation encapsulates the essence of deception — a multifaceted labyrinth wherein the exterior façade promises expansiveness, while the internal reality reveals a confined and elemental space, challenging preconceived notions and inviting contemplation on the intricacies of duplicity`, src:'https://i.ibb.co/M1XxzrW/deception.jpg',imgs:['https://i.ibb.co/4d0qgzr/deception.jpg'], tag:"art"},

    {id:9, name: 'Cloud Box', date: '2020', description: `This artistic endeavor serves as a meticulous inquiry into the dichotomy between rigid and fluid forms. In this endeavor, the artist seeks to unravel the inherent tension and harmony existing within the juxtaposition of rigid and fluid elements `, src:'https://i.ibb.co/xSmv9s1/b-w-cloud-box.jpg',imgs:['https://i.ibb.co/7gt40MM/b-w-cloud-box.jpg'], tag:"art"},

    {id:10, name: 'Column', date: '2019', description: `The artwork unfolds within the confines of a cubic domain, where abstract apertures and arches defy the constraints of a conventional, realistic perspective. The deliberate departure from perceptual norms serves as a deliberate venture into a realm where geometric rigidity coexists with abstract dissonance, challenging the observer to engage with the cognitive dissonance inherent in the nonconformity of architectural elements.`, src:'https://i.ibb.co/G9Jftf2/column.jpg',imgs:['https://i.ibb.co/gWSHRS0/column.jpg'], tag:"art"},

    {id:11, name: 'Box', date: '2020', description: `An aesthetic exploration that seeks to redefine the essential character of the box`, src:'https://i.ibb.co/m0yMn4V/b-w-box.jpg]',imgs:['https://i.ibb.co/6Y6XR53/b-w-box.jpg'], tag:"art"},

    {id:12, name: 'The Shadow', date: '2019', description: `Within this drawing, a conceptual exploration unfolds the intricate interplay between a one-dimensional form and its projection shadow in three dimensions. The form, rendered in a stark black, serves as a visual anchor, while the shadow, endowed with vibrant color and adorned by a discernible pattern, delineates an immersive narrative of dimensional translation `, src:'https://i.ibb.co/6FZ2Fbg/the-shadow.jpg',imgs:['https://i.ibb.co/cxpMRHG/the-shadow.jpg'], tag:"art"},

    {id:13, name: 'The Tower', date: '2020', description: `This artwork undertakes a reimagining of the Tugrul Tower situated in Rey, Iran, within the context of a contemporary landscape. The reinterpretation gracefully integrates modern elements and architectural aesthetics, thereby breathing new life into an ancient structure. Through this visual narrative, the artist navigates the intersection of history and modernity, inviting viewers to engage with the evolving tapestry of time and culture as embodied by the revitalized presence of Tugrul Tower within a dynamic, contemporary milieu.`, src:'https://i.ibb.co/SyL2Z5P/togrul-tower.jpg',imgs:['https://i.ibb.co/RNSbdss/togrul-tower.jpg'], tag:"art"},

    {id:14, name: 'Gates To Heaven', date: '2023', description: `
    This artwork serves as a poignant commentary on the prevailing political landscape in Iran, symbolically portraying the pervasive influence of authoritarianism. It articulates a stark juxtaposition wherein religious constraints seemingly pave a stairway to heaven, paradoxically composed of the poignant elements of blood and women's hair—an allegorical representation of the sacrifices and struggles endured by women as they navigate a path to freedom within the oppressive context of religious doctrine `, src:'https://i.ibb.co/Ns5zC20/heaven-gate.jpg',imgs:['https://i.ibb.co/9bFLyQS/heaven-gate.jpg'],tag:"art"},

    {id:15, name: 'The Family', date: '2020', description: `This artistic endeavor constitutes a nuanced exploration into the realms of form, color, and texture using the medium of air-dry clay. `, src:'https://i.ibb.co/dtpHccM/the-family.jpg',imgs:['https://i.ibb.co/GC3cwdy/image-50402561.jpg'], tag:"art"},

    {id:16, name: 'Form Study-01', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/xhZvS31/form-stydu-01.jpg',imgs:['https://i.ibb.co/7pbLCS9/form-stydu-01.jpg'], tag:"art"},

    {id:17, name: 'Form Study-02', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/FBG2Qrj/form-study-02.jpg',imgs:['https://i.ibb.co/y5QfkTp/form-study-02.jpg'], tag:"art"},

    {id:18, name: 'Form Study-03', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/c8pPk7n/form-study-03.jpg',imgs:['https://i.ibb.co/PD3HHWK/form-study-03.jpg'], tag:"art"},

    {id:19, name: 'Form Study-04', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/CsHkRBM/fomr-study-07.jpg',imgs:['https://i.ibb.co/Fmf7XK7/fomr-study-07.jpg'], tag:"art"},

    {id:20, name: 'Form Study-05', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/df4VpjM/fomr-study-04.jpg',iimgs:['https://i.ibb.co/S5F3GZw/fomr-study-04.jpg'], tag:"art"},

    {id:21, name: 'Form Study-06', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/Qm6zDs5/fomr-study-06.jpg',imgs:['https://i.ibb.co/rvXsXMQ/fomr-study-06.jpg'], tag:"art"},


    {id:22, name: 'Form Study-07', date: '2019', description: `This artwork is a part of a series of drawings which delves into the nuanced realms of form and perspective. Positioned within a deliberate exploration and investigation, each piece in this collection serves as a cogent inquiry into the complexities inherent in shaping visual narratives through the interplay of form and perspective`, src:'https://i.ibb.co/g6KXm0X/fomr-study-05.png',imgs:['https://i.ibb.co/Y3McRdj/fomr-study-05.png'], tag:"art"},

    {id:23, name: 'The Killing', date: '2022', description: `Through the utilization of air-dry clay and interwoven strings, this artwork encapsulates an exploration of the palpable and intricate sensation of oppression prevalent in Iran. The symbiotic integration of materials materializes a form that poignantly embodies the complex interplay of constricting forces and entwining threads, conveying the strangling essence of oppression.`, src:'https://i.ibb.co/fFt2ZG8/the-killing.jpg',imgs:['https://i.ibb.co/L1kXghB/the-killing.jpg'], tag:"art"},

    {id:24, name: 'A Play :: The Missing', date: '2022', description: `This theatrical production, crafted in the spirit of the Woman, Life, Freedom movement in Iran, serves as a synthesis of personal and collective narratives. Conceived, written, and performed by myself, an Iranian immigrant woman, in collaboration with my esteemed American actor colleagues, the piece transcends geographical boundaries to articulate the universal essence of suffering and pain. Through the portrayal of characters navigating life far from Iran, the production illuminates the genuineness of the human experience, underscoring the poignant reality that the enduring ache is a shared and authentic facet of the human condition, irrespective of individual backgrounds or cultural origins`, src:'https://i.ibb.co/7zLVH1D/the-missing.jpg',imgs:['https://i.ibb.co/XY4KKfX/the-missing.jpg'], tag:"art"},

    {id:25, name: 'A Play :: Kings Go South', date: '2023', description: `In the theatrical rendition helmed by Peter Temes, I assumed the character of Teddy, a woman in her 50s. Rooted in meticulous research and historical veracity, this performance unfolds as an evocative exploration of the lesser-known facets of Martin Luther King Jr.'s life before achieving widespread recognition.`, src:'https://i.ibb.co/TRVQ5FG/kings-go-south.jpg',imgs:['https://i.ibb.co/Bjc1zd4/kings-go-south.jpg'], tag:"art"},

    {id:26, name: 'A Play :: Plastic Roses', date: '2023', description: `I contributed to a workshop production skillfully penned by Valentine Wulf, in a role as Meemaw, hosted within the esteemed confines of Theater Puget Sound.`, src:'https://i.ibb.co/nB5Nm2z/plastic-roses.jpg',imgs:['https://i.ibb.co/n3R4gQY/plastic-roses.jpg'], tag:"art"},
]
